# Site settings
header-img: img/home-bg.png
copyright_name: Blah Cats
title: BlahCat 4 Lyfe
email: ctf AT [nospam]blah DOT cat
description: >

  void live(){ eat(); sleep(); hack(); live(); }

baseurl: ""
url: "https://blahcat.github.io"
email_username:  ctf AT [nospam]blah DOT cat
twitter_username: ctf_blahcat
github_username:  blahcat

excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
